
DROP TRIGGER EVENTS_TS_TRIGGER;
DROP TABLE EVENTS;

CREATE TABLE "&&SCHEMA_NAME"."EVENTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EVENT_TS" TIMESTAMP (6), 
	"EVENT_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE" VARCHAR2(1024 BYTE) COLLATE "USING_NLS_COMP", 
	"IP_ADDRESS" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "&&SCHEMA_NAME"."EVENTS_PK" ON "&&SCHEMA_NAME"."EVENTS" ("ID") 
  ;

ALTER TABLE "&&SCHEMA_NAME"."EVENTS" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "&&SCHEMA_NAME"."EVENTS" ADD CONSTRAINT "EVENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

ALTER TABLE "&&SCHEMA_NAME"."EVENTS" MODIFY ("EVENT_TS" NOT NULL ENABLE);

CREATE OR REPLACE EDITIONABLE TRIGGER "&&SCHEMA_NAME"."EVENTS_TS_TRIGGER" 
BEFORE INSERT OR UPDATE ON texteck_dev.events
FOR EACH ROW
BEGIN
    if :old.event_ts is null then
       :new.event_ts := SYSTIMESTAMP;
    end if;
END;


